In [1]:
import pandas as pd
import datetime

def doy(r,col_name="Date"):
    return datetime.datetime(int(r[col_name][:4]), int(r[col_name][5:7]), int(r[col_name][8:10])).timetuple().tm_yday

r = pd.read_excel("Ames_Brooks_Data.xlsx",sheetname="Met_Data")
r=r[['TimeStamp','Air Temp (◦F)']]
r.iloc[:,0]=r.applymap(str).iloc[:,0]
r['Date'] = r.TimeStamp.str[:11]
r['Year'] = r.TimeStamp.str[:4]
r['DOY'] = pd.Series.to_frame(r.apply(doy,axis=1))
r=r.loc[r['Year'].isin(['2002','2003','2004','2005'])]
r['temp(C)']=5*(r['Air Temp (◦F)']-32)/9
r=r[['Date','Year','DOY','temp(C)']]

In [2]:
df=r.groupby('Date')['temp(C)'].max().reset_index()
df.columns=["Date",'tmax']
df['tmin']=r.groupby('Date')['temp(C)'].min().reset_index()['temp(C)']
df['Year'] = df.Date.str[:4]
df['DOY'] = pd.Series.to_frame(df.apply(doy,axis=1))
df

             Date       tmax       tmin  Year  DOY
0     2002-01-01   -8.950000 -14.940000  2002    1
1     2002-01-02   -6.466111 -13.330000  2002    2
2     2002-01-03   -1.402222 -16.020000  2002    3
3     2002-01-04    5.037222  -6.943889  2002    4
4     2002-01-05    5.655000  -4.702222  2002    5
5     2002-01-06   -0.695000 -11.660000  2002    6
6     2002-01-07    1.210000 -15.670000  2002    7
7     2002-01-08   17.210000  -3.602222  2002    8
8     2002-01-09   12.630000   2.611111  2002    9
9     2002-01-10    3.972222  -0.338889  2002   10
10    2002-01-11   11.970000  -6.497778  2002   11
11    2002-01-12    5.522778  -4.008889  2002   12
12    2002-01-13   10.150000  -3.670000  2002   13
13    2002-01-14    3.320000  -1.906111  2002   14
14    2002-01-15   -2.960000  -5.626111  2002   15
15    2002-01-16   -3.132778  -9.980000  2002   16
16    2002-01-17    0.576111 -10.360000  2002   17
17    2002-01-18   -4.925000 -13.000000  2002   18
18    2002-01-19    1.730000  -8.510000  2002   19
19    2002-01-20    6.862778  -7.730000  2002   20
20    2002-01-21    9.310000  -8.170000  2002   21
21    2002-01-22   13.790000  -2.781111  2002   22
22    2002-01-23    1.430000  -7.930000  2002   23
23    2002-01-24    7.780000 -14.440000  2002   24
24    2002-01-25   15.390000  -6.232222  2002   25
25    2002-01-26   18.920000   1.317778  2002   26
26    2002-01-27   13.830000  -3.610000  2002   27
27    2002-01-28   -1.772222  -5.987778  2002   28
28    2002-01-29   -3.323889  -6.472778  2002   29
29    2002-01-30   -3.387222  -8.030000  2002   30
...           ...        ...        ...   ...  ...
1431  2005-12-02  -10.280000 -14.560000  2005  336
1432  2005-12-03   -7.960000 -10.260000  2005  337
1433  2005-12-04  -10.000000 -18.580000  2005  338
1434  2005-12-05  -12.550000 -23.000000  2005  339
1435  2005-12-06  -15.710000 -21.450000  2005  340
1436  2005-12-07  -15.630000 -23.250000  2005  341
1437  2005-12-08  -10.160000 -21.320000  2005  342
1438  2005-12-09  -10.420000 -24.760000  2005  343
1439  2005-12-10    1.691111  -9.560000  2005  344
1440  2005-12-11    1.103889  -2.212222  2005  345
1441  2005-12-12    2.103889  -5.185000  2005  346
1442  2005-12-13    2.015000  -7.890000  2005  347
1443  2005-12-14    1.367778  -0.037778  2005  348
1444  2005-12-15    0.226111  -6.485000  2005  349
1445  2005-12-16   -6.261111 -10.830000  2005  350
1446  2005-12-17  -10.070000 -16.020000  2005  351
1447  2005-12-18  -11.960000 -15.450000  2005  352
1448  2005-12-19   -7.990000 -19.620000  2005  353
1449  2005-12-20   -6.387222 -15.310000  2005  354
1450  2005-12-21   -3.816111 -16.180000  2005  355
1451  2005-12-22    4.402222  -6.655000  2005  356
1452  2005-12-23    3.118889  -2.122778  2005  357
1453  2005-12-24    2.317778   0.276111  2005  358
1454  2005-12-25    0.182222  -1.387222  2005  359
1455  2005-12-26    0.122778  -2.551111  2005  360
1456  2005-12-27   -0.517778  -1.890000  2005  361
1457  2005-12-28   -0.320000  -1.691111  2005  362
1458  2005-12-29    0.091111  -2.020000  2005  363
1459  2005-12-30    0.702778  -0.917222  2005  364
1460  2005-12-31    0.210000  -2.342222  2005  365

[1461 rows x 5 columns]

In [3]:
daily = pd.read_excel("Ames_Brooks_Data.xlsx",sheetname="Met_Data2")
daily=daily[['Date','High Air Temp (°C)','Low Air Temp (°C)']]
daily.columns=['Date','tmax','tmin']
daily.loc[:,'Date']=daily.applymap(str).loc[:,'Date']
daily['Date'] = daily.Date.str[:11]
daily['Year'] = daily.Date.str[:4]
daily['DOY'] = pd.Series.to_frame(daily.apply(doy,axis=1))
daily

             Date       tmax       tmin  Year  DOY
0     2006-01-01    2.986111  -3.092222  2006    1
1     2006-01-02    1.263889   0.111111  2006    2
2     2006-01-03    1.500000  -0.125000  2006    3
3     2006-01-04    4.202778  -0.398889  2006    4
4     2006-01-05   -0.417778  -5.122222  2006    5
5     2006-01-06    0.850000  -6.002778  2006    6
6     2006-01-07    6.655000  -2.102778  2006    7
7     2006-01-08    1.357222  -1.166111  2006    8
8     2006-01-09    0.158889  -7.990000  2006    9
9     2006-01-10    2.280000  -9.200000  2006   10
10    2006-01-11    8.620000  -5.198889  2006   11
11    2006-01-12    8.650000  -1.506111  2006   12
12    2006-01-13    0.402778  -5.335000  2006   13
13    2006-01-14    6.797778  -8.230000  2006   14
14    2006-01-15   12.540000  -1.013889  2006   15
15    2006-01-16    2.478889  -4.632222  2006   16
16    2006-01-17   -2.825000  -6.138889  2006   17
17    2006-01-18    8.940000  -9.700000  2006   18
18    2006-01-19    7.670000  -3.233889  2006   19
19    2006-01-20   -1.297778  -4.335000  2006   20
20    2006-01-21   -1.621111  -4.688889  2006   21
21    2006-01-22    0.082222 -11.250000  2006   22
22    2006-01-23    2.117778 -12.000000  2006   23
23    2006-01-24    4.715000  -4.938889  2006   24
24    2006-01-25    5.273889  -7.290000  2006   25
25    2006-01-26   15.090000  -4.391111  2006   26
26    2006-01-27   13.960000   1.928889  2006   27
27    2006-01-28    6.801111   3.527778  2006   28
28    2006-01-29    5.307222   0.377222  2006   29
29    2006-01-30    1.472778  -0.692778  2006   30
...           ...        ...        ...   ...  ...
2892  2013-12-02    7.420000  -0.451111  2013  336
2893  2013-12-03    3.045000  -0.366111  2013  337
2894  2013-12-04    2.846111  -8.950000  2013  338
2895  2013-12-05   -8.890000 -15.160000  2013  339
2896  2013-12-06  -11.200000 -18.690000  2013  340
2897  2013-12-07  -11.420000 -20.870000  2013  341
2898  2013-12-08   -8.370000 -12.520000  2013  342
2899  2013-12-09  -10.720000 -20.920000  2013  343
2900  2013-12-10   -7.490000 -15.840000  2013  344
2901  2013-12-11   -8.110000 -21.010000  2013  345
2902  2013-12-12   -2.995000 -17.810000  2013  346
2903  2013-12-13   -2.395000 -11.230000  2013  347
2904  2013-12-14   -5.763889 -12.580000  2013  348
2905  2013-12-15  -10.010000 -13.420000  2013  349
2906  2013-12-16   -3.617222 -11.680000  2013  350
2907  2013-12-17    0.791111 -10.110000  2013  351
2908  2013-12-18    7.540000  -9.440000  2013  352
2909  2013-12-19    2.145000  -4.776111  2013  353
2910  2013-12-20   -4.187778  -7.350000  2013  354
2911  2013-12-21   -4.705000  -9.020000  2013  355
2912  2013-12-22   -4.848889 -15.700000  2013  356
2913  2013-12-23  -14.870000 -21.760000  2013  357
2914  2013-12-24   -9.540000 -26.150000  2013  358
2915  2013-12-25    0.122778  -9.530000  2013  359
2916  2013-12-26    1.523889  -8.710000  2013  360
2917  2013-12-27    6.337222 -10.290000  2013  361
2918  2013-12-28    9.250000  -5.730000  2013  362
2919  2013-12-29   -5.778889 -19.340000  2013  363
2920  2013-12-30  -12.020000 -19.940000  2013  364
2921  2013-12-31  -12.840000 -17.670000  2013  365

[2922 rows x 5 columns]

In [4]:
temp_data=pd.concat([df,daily])
temp_data.index=range(1,1+len(temp_data.index))
temp_data

             Date       tmax       tmin  Year  DOY
1     2002-01-01   -8.950000 -14.940000  2002    1
2     2002-01-02   -6.466111 -13.330000  2002    2
3     2002-01-03   -1.402222 -16.020000  2002    3
4     2002-01-04    5.037222  -6.943889  2002    4
5     2002-01-05    5.655000  -4.702222  2002    5
6     2002-01-06   -0.695000 -11.660000  2002    6
7     2002-01-07    1.210000 -15.670000  2002    7
8     2002-01-08   17.210000  -3.602222  2002    8
9     2002-01-09   12.630000   2.611111  2002    9
10    2002-01-10    3.972222  -0.338889  2002   10
11    2002-01-11   11.970000  -6.497778  2002   11
12    2002-01-12    5.522778  -4.008889  2002   12
13    2002-01-13   10.150000  -3.670000  2002   13
14    2002-01-14    3.320000  -1.906111  2002   14
15    2002-01-15   -2.960000  -5.626111  2002   15
16    2002-01-16   -3.132778  -9.980000  2002   16
17    2002-01-17    0.576111 -10.360000  2002   17
18    2002-01-18   -4.925000 -13.000000  2002   18
19    2002-01-19    1.730000  -8.510000  2002   19
20    2002-01-20    6.862778  -7.730000  2002   20
21    2002-01-21    9.310000  -8.170000  2002   21
22    2002-01-22   13.790000  -2.781111  2002   22
23    2002-01-23    1.430000  -7.930000  2002   23
24    2002-01-24    7.780000 -14.440000  2002   24
25    2002-01-25   15.390000  -6.232222  2002   25
26    2002-01-26   18.920000   1.317778  2002   26
27    2002-01-27   13.830000  -3.610000  2002   27
28    2002-01-28   -1.772222  -5.987778  2002   28
29    2002-01-29   -3.323889  -6.472778  2002   29
30    2002-01-30   -3.387222  -8.030000  2002   30
...           ...        ...        ...   ...  ...
4354  2013-12-02    7.420000  -0.451111  2013  336
4355  2013-12-03    3.045000  -0.366111  2013  337
4356  2013-12-04    2.846111  -8.950000  2013  338
4357  2013-12-05   -8.890000 -15.160000  2013  339
4358  2013-12-06  -11.200000 -18.690000  2013  340
4359  2013-12-07  -11.420000 -20.870000  2013  341
4360  2013-12-08   -8.370000 -12.520000  2013  342
4361  2013-12-09  -10.720000 -20.920000  2013  343
4362  2013-12-10   -7.490000 -15.840000  2013  344
4363  2013-12-11   -8.110000 -21.010000  2013  345
4364  2013-12-12   -2.995000 -17.810000  2013  346
4365  2013-12-13   -2.395000 -11.230000  2013  347
4366  2013-12-14   -5.763889 -12.580000  2013  348
4367  2013-12-15  -10.010000 -13.420000  2013  349
4368  2013-12-16   -3.617222 -11.680000  2013  350
4369  2013-12-17    0.791111 -10.110000  2013  351
4370  2013-12-18    7.540000  -9.440000  2013  352
4371  2013-12-19    2.145000  -4.776111  2013  353
4372  2013-12-20   -4.187778  -7.350000  2013  354
4373  2013-12-21   -4.705000  -9.020000  2013  355
4374  2013-12-22   -4.848889 -15.700000  2013  356
4375  2013-12-23  -14.870000 -21.760000  2013  357
4376  2013-12-24   -9.540000 -26.150000  2013  358
4377  2013-12-25    0.122778  -9.530000  2013  359
4378  2013-12-26    1.523889  -8.710000  2013  360
4379  2013-12-27    6.337222 -10.290000  2013  361
4380  2013-12-28    9.250000  -5.730000  2013  362
4381  2013-12-29   -5.778889 -19.340000  2013  363
4382  2013-12-30  -12.020000 -19.940000  2013  364
4383  2013-12-31  -12.840000 -17.670000  2013  365

[4383 rows x 5 columns]

In [52]:
#temp_data.to_pickle("Temperature_data_2002to2013_Site_10_11")

In [11]:
import pandas as pd
temp_data=pd.read_pickle("Temperature_data_2002to2013_Site_10_11")
temp_data['tmin_corn'] = temp_data.tmin.clip(8.0,30.0)
temp_data['tmax_corn'] = temp_data.tmax.clip(8.0,30.0)
temp_data['tmin_soy'] = temp_data.tmin.clip(10.0,25.0)
temp_data['tmax_soy'] = temp_data.tmax.clip(10.0,25.0)
temp_data['tavg_corn']=0.5*(temp_data.tmin_corn+temp_data.tmax_corn)
temp_data['tavg_soy']=0.5*(temp_data.tmin_soy+temp_data.tmax_soy)
temp_data['gdd_corn']=temp_data['tavg_corn']-8.0
temp_data['gdd_soy']=temp_data['tavg_soy']-10.0
temp_data
temp_data.to_pickle("GDD_Temperature_data_2002to2013_Site_10_11")

#pd.concat([temp_data, pd.concat([df4], keys=["tmin"])])

In [15]:
temp_data.to_csv("GDD_Temperature_data_2002to2013_Site_10_11.csv")

In [16]:
temp_data

,Date,tmax,tmin,Year,DOY,tmin_corn,tmax_corn,tmin_soy,tmax_soy,tavg_corn,tavg_soy,gdd_corn,gdd_soy
1,2002-01-01,-8.950000,-14.940000,2002,1,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
2,2002-01-02,-6.466111,-13.330000,2002,2,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
3,2002-01-03,-1.402222,-16.020000,2002,3,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4,2002-01-04,5.037222,-6.943889,2002,4,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
5,2002-01-05,5.655000,-4.702222,2002,5,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
6,2002-01-06,-0.695000,-11.660000,2002,6,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
7,2002-01-07,1.210000,-15.670000,2002,7,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
8,2002-01-08,17.210000,-3.602222,2002,8,8.0,17.21,10.0,17.21,12.605,13.605,4.605,3.605
9,2002-01-09,12.630000,2.611111,2002,9,8.0,12.63,10.0,12.63,10.315,11.315,2.315,1.315
10,2002-01-10,3.972222,-0.338889,2002,10,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
11,2002-01-11,11.970000,-6.497778,2002,11,8.0,11.97,10.0,11.97,9.985,10.985,1.985,0.985
12,2002-01-12,5.522778,-4.008889,2002,12,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
13,2002-01-13,10.150000,-3.670000,2002,13,8.0,10.15,10.0,10.15,9.075,10.075,1.075,0.075
14,2002-01-14,3.320000,-1.906111,2002,14,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
15,2002-01-15,-2.960000,-5.626111,2002,15,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
16,2002-01-16,-3.132778,-9.980000,2002,16,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
17,2002-01-17,0.576111,-10.360000,2002,17,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
18,2002-01-18,-4.925000,-13.000000,2002,18,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
19,2002-01-19,1.730000,-8.510000,2002,19,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
20,2002-01-20,6.862778,-7.730000,2002,20,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
21,2002-01-21,9.310000,-8.170000,2002,21,8.0,9.31,10.0,10.00,8.655,10.000,0.655,0.000
22,2002-01-22,13.790000,-2.781111,2002,22,8.0,13.79,10.0,13.79,10.895,11.895,2.895,1.895
23,2002-01-23,1.430000,-7.930000,2002,23,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
24,2002-01-24,7.780000,-14.440000,2002,24,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
25,2002-01-25,15.390000,-6.232222,2002,25,8.0,15.39,10.0,15.39,11.695,12.695,3.695,2.695
26,2002-01-26,18.920000,1.317778,2002,26,8.0,18.92,10.0,18.92,13.460,14.460,5.460,4.460
27,2002-01-27,13.830000,-3.610000,2002,27,8.0,13.83,10.0,13.83,10.915,11.915,2.915,1.915
28,2002-01-28,-1.772222,-5.987778,2002,28,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
29,2002-01-29,-3.323889,-6.472778,2002,29,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
30,2002-01-30,-3.387222,-8.030000,2002,30,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4354,2013-12-02,7.420000,-0.451111,2013,336,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4355,2013-12-03,3.045000,-0.366111,2013,337,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4356,2013-12-04,2.846111,-8.950000,2013,338,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4357,2013-12-05,-8.890000,-15.160000,2013,339,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4358,2013-12-06,-11.200000,-18.690000,2013,340,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4359,2013-12-07,-11.420000,-20.870000,2013,341,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4360,2013-12-08,-8.370000,-12.520000,2013,342,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4361,2013-12-09,-10.720000,-20.920000,2013,343,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4362,2013-12-10,-7.490000,-15.840000,2013,344,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4363,2013-12-11,-8.110000,-21.010000,2013,345,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4364,2013-12-12,-2.995000,-17.810000,2013,346,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4365,2013-12-13,-2.395000,-11.230000,2013,347,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4366,2013-12-14,-5.763889,-12.580000,2013,348,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4367,2013-12-15,-10.010000,-13.420000,2013,349,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4368,2013-12-16,-3.617222,-11.680000,2013,350,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4369,2013-12-17,0.791111,-10.110000,2013,351,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4370,2013-12-18,7.540000,-9.440000,2013,352,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4371,2013-12-19,2.145000,-4.776111,2013,353,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4372,2013-12-20,-4.187778,-7.350000,2013,354,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4373,2013-12-21,-4.705000,-9.020000,2013,355,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4374,2013-12-22,-4.848889,-15.700000,2013,356,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4375,2013-12-23,-14.870000,-21.760000,2013,357,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4376,2013-12-24,-9.540000,-26.150000,2013,358,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4377,2013-12-25,0.122778,-9.530000,2013,359,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4378,2013-12-26,1.523889,-8.710000,2013,360,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4379,2013-12-27,6.337222,-10.290000,2013,361,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4380,2013-12-28,9.250000,-5.730000,2013,362,8.0,9.25,10.0,10.00,8.625,10.000,0.625,0.000
4381,2013-12-29,-5.778889,-19.340000,2013,363,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4382,2013-12-30,-12.020000,-19.940000,2013,364,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000
4383,2013-12-31,-12.840000,-17.670000,2013,365,8.0,8.00,10.0,10.00,8.000,10.000,0.000,0.000

In [88]:
gdd_corn_green=340
gdd_soy_green=400
gdd_corn_sen=150
gdd_soy_sen=260

g10=[159,189,181,162,186,169,183,159,158,163,166,169]#,185,164]
s10=[248,256,269,240,257,256,252,271,247,255,233,266]#,263,257]
g11=[163,188,161,159,162,172,181,159,157,165,166,199]#,161,172]
s11=[218,253,271,242,243,254,251,224,247,258,246,265]#,263,260]

def gdd_backcalculation(green,sen,gdd_corn_green,gdd_soy_green,gdd_corn_sen,gdd_soy_sen):
    p_corn=[]
    p_soy=[]
    h_corn=[]
    h_soy=[]
    for i in range(len(green)) :
        yr=str(2002+i)
        g=green[i]
        s=sen[i]

        t=temp_data.loc[(temp_data.Year==yr) & (temp_data.DOY<=g)]
        t.index=range(1,1+len(t))
        t['gdd_corn_cum']=t.loc[::-1, 'gdd_corn'].cumsum()[::-1]
        t['gdd_soy_cum']=t.loc[::-1, 'gdd_soy'].cumsum()[::-1]
        c_cum=t['gdd_corn_cum']
        s_cum=t['gdd_soy_cum']
        corn=c_cum[c_cum<gdd_corn_green]
        soy=s_cum[s_cum<gdd_soy_green]
        p_corn.append(corn.index[0]-1 if(corn.index[0]>1) else 100)
        p_soy.append(soy.index[0]-1 if(soy.index[0]>1) else 100)

        t=temp_data.loc[(temp_data.Year==yr) & (temp_data.DOY>=s)]
        t.index=range(s,s+len(t))
        t['gdd_corn_cum']=t.loc[:,'gdd_corn'].cumsum()
        t['gdd_soy_cum']=t.loc[:,'gdd_soy'].cumsum()
        c_cum=t['gdd_corn_cum']
        s_cum=t['gdd_soy_cum']
        corn=c_cum[c_cum>gdd_corn_sen]
        soy=s_cum[s_cum>gdd_soy_sen]
        h_corn.append(corn.index[0] if len(corn.index>0) else 320)
        h_soy.append(soy.index[0] if len(soy.index>0) else 320)
    return (p_corn,p_soy,h_corn,h_soy)
p10_corn,p10_soy,h10_corn,h10_soy=gdd_backcalculation(g10,s10,gdd_corn_green,gdd_soy_green,gdd_corn_sen,gdd_soy_sen)
p11_corn,p11_soy,h11_corn,h11_soy=gdd_backcalculation(g11,s11,gdd_corn_green,gdd_soy_green,gdd_corn_sen,gdd_soy_sen)

C:\Users\koutilya\AppData\Local\Continuum\Anaconda3\envs\CCMS\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\koutilya\AppData\Local\Continuum\Anaconda3\envs\CCMS\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\koutilya\AppData\Local\Continuum\Anaconda3\envs\CCMS\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\koutilya\AppData\Local\Continuum\Anaconda3\envs\CCMS\lib\site-packages\ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [89]:
print(p10_corn)
print(h10_corn)
print(p11_corn)
print(h11_corn)

[114, 166, 151, 127, 162, 142, 157, 119, 123, 129, 138, 137]
[260, 279, 298, 251, 276, 272, 267, 335, 261, 277, 243, 281]
[127, 165, 128, 117, 135, 147, 155, 119, 121, 131, 138, 178]
[230, 272, 302, 252, 258, 270, 267, 235, 261, 279, 259, 280]

In [90]:
print(p10_soy)
print(h10_soy)
print(p11_soy)
print(h11_soy)

[100, 147, 132, 95, 148, 125, 138, 100, 91, 100, 116, 97]
[286, 320, 320, 266, 320, 302, 290, 320, 283, 318, 260, 320]
[54, 146, 94, 88, 102, 129, 135, 100, 90, 100, 116, 166]
[243, 334, 320, 268, 288, 296, 287, 254, 283, 320, 289, 320]