In [140]:
import pandas as pd
import numpy as np

In [141]:
crop_info=pd.read_excel("../Nebraska_Planting&Harvesting.xlsx",sheetname='crop_info')
lai=pd.read_excel("Ameriflux Final Crop Data Set - 2001 to 2016.xlsx",skiprows=[0,1,2,3,4])
lai=lai.drop([0])
lai = lai.drop(['Sample Date','Canopy Height'], 1)
lai = lai[np.isfinite(lai['Year'])]
lai[['Year','Site','Sample\n(DOY)']]=lai[['Year','Site','Sample\n(DOY)']].astype(int)
lai=pd.merge(lai, crop_info,  how='left', left_on=['Year','Site'], right_on = ['Year','Site'])
lai

     Year  Site  Sample\n(DOY) Green\nLeaf\nLAI\n  Crop
0    2001     1            149          0.0280863     1
1    2001     1            164           0.369112     1
2    2001     1            172            1.29104     1
3    2001     1            180             2.9447     1
4    2001     1            186            5.23946     1
5    2001     1            193            6.03694     1
6    2001     1            200            6.07868     1
7    2001     1            220             5.6927     1
8    2001     1            227            5.37085     1
9    2001     2            149          0.0155399     1
10   2001     2            164            0.31544     1
11   2001     2            172            1.02502     1
12   2001     2            180             2.6713     1
13   2001     2            190            5.27396     1
14   2001     2            193            6.07975     1
15   2001     2            201            6.07038     1
16   2001     2            220            5.86785     1
17   2001     2            232            5.64467     1
18   2001     3            149         0.00829956     1
19   2001     3            164           0.179909     1
20   2001     3            172           0.698763     1
21   2001     3            179            1.86674     1
22   2001     3            186            2.98488     1
23   2001     3            192            3.88221     1
24   2001     3            199            3.82949     1
25   2001     3            219            3.51071     1
26   2001     3            226            3.06002     1
27   2002     1            149          0.0111055     1
28   2002     1            154           0.037466     1
29   2002     1            169           0.971284     1
..    ...   ...            ...                ...   ...
549  2016     2            149                  0     2
550  2016     2            158          0.0571144     2
551  2016     2            165           0.174081     2
552  2016     2            172           0.345303     2
553  2016     2            179           0.838478     2
554  2016     2            187            1.11547     2
555  2016     2            193            1.76878     2
556  2016     2            200            2.92972     2
557  2016     2            207            4.47334     2
558  2016     2            214            4.66885     2
559  2016     2            221            5.09577     2
560  2016     2            228            4.77253     2
561  2016     2            236            4.62399     2
562  2016     2            256            3.73106     2
563  2016     2            277          0.0876706     2
564  2016     3            150                  0     2
565  2016     3            158          0.0477973     2
566  2016     3            166            0.14652     2
567  2016     3            173            0.20489     2
568  2016     3            182            1.02088     2
569  2016     3            189            1.11185     2
570  2016     3            195            2.04535     2
571  2016     3            202            2.43293     2
572  2016     3            209            3.25703     2
573  2016     3            216            4.25422     2
574  2016     3            223            4.60588     2
575  2016     3            230            4.62898     2
576  2016     3            250            4.08444     2
577  2016     3            264            3.06765     2
578  2016     3            279          0.0144714     2

[579 rows x 5 columns]

In [142]:
temp=pd.read_csv("meads_bands/ne1_corn.csv").drop('Unnamed: 0',1)
temp['crop']=1
temp['site']=1
meads_data=temp

temp=pd.read_csv("meads_bands/ne1_soy.csv").drop('Unnamed: 0',1)
temp['crop']=2
temp['site']=1
meads_data=meads_data.append(temp,ignore_index=True)

temp=pd.read_csv("meads_bands/ne2_corn.csv").drop('Unnamed: 0',1)
temp['crop']=1
temp['site']=2
meads_data=meads_data.append(temp,ignore_index=True)

temp=pd.read_csv("meads_bands/ne2_soy.csv").drop('Unnamed: 0',1)
temp['crop']=2
temp['site']=2
meads_data=meads_data.append(temp,ignore_index=True)

temp=pd.read_csv("meads_bands/ne3_corn.csv").drop('Unnamed: 0',1)
temp['crop']=1
temp['site']=3
meads_data=meads_data.append(temp,ignore_index=True)

temp=pd.read_csv("meads_bands/ne3_soy.csv").drop('Unnamed: 0',1)
temp['crop']=2
temp['site']=3
meads_data=meads_data.append(temp,ignore_index=True)

meads_data

,doy,2001_b1,2001_b2,2002_b1,2002_b2,2003_b1,2003_b2,2004_b1,2004_b2,2005_b1,...,2013_b1,2013_b2,2014_b1,2014_b2,2015_b1,2015_b2,2016_b1,2016_b2,crop,site
0,1,NaN,NaN,1818.128469,2857.315671,1879.196199,3108.177411,1672.854938,2708.475203,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
1,2,NaN,NaN,1818.128469,2857.315671,1879.196199,3108.177411,1672.854938,2708.475203,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
2,3,NaN,NaN,1818.128469,2857.315671,1879.196199,3108.177411,1672.854938,2708.475203,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
3,4,NaN,NaN,1818.128469,2857.315671,1879.196199,3108.177411,1672.854938,2708.475203,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
4,5,NaN,NaN,1818.128469,2857.315671,1879.196199,3108.177411,1672.854938,2708.475203,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
5,6,NaN,NaN,1818.128469,2857.315671,1879.196199,3108.177411,1672.854938,2708.475203,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
6,7,NaN,NaN,1818.128469,2857.315671,1879.196199,3108.177411,1672.854938,2708.475203,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
7,8,NaN,NaN,1818.128469,2857.315671,1879.196199,3108.177411,1672.854938,2708.475203,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
8,9,NaN,NaN,1750.179260,2781.444355,1832.953267,2937.284047,1877.838227,2856.621684,NaN,...,NaN,NaN,1485.035260,2423.749044,1431.812097,2331.062515,NaN,NaN,1,1
9,10,NaN,NaN,1750.179260,2781.444355,1832.953267,2937.284047,1877.838227,2856.621684,NaN,...,NaN,NaN,1485.035260,2423.749044,1431.812097,2331.062515,NaN,NaN,1,1
10,11,NaN,NaN,1750.179260,2781.444355,1832.953267,2937.284047,1877.838227,2856.621684,NaN,...,NaN,NaN,1485.035260,2423.749044,1431.812097,2331.062515,NaN,NaN,1,1
11,12,NaN,NaN,1750.179260,2781.444355,1832.953267,2937.284047,1877.838227,2856.621684,NaN,...,NaN,NaN,1485.035260,2423.749044,1431.812097,2331.062515,NaN,NaN,1,1
12,13,NaN,NaN,1750.179260,2781.444355,1832.953267,2937.284047,1877.838227,2856.621684,NaN,...,NaN,NaN,1485.035260,2423.749044,1431.812097,2331.062515,NaN,NaN,1,1
13,14,NaN,NaN,1750.179260,2781.444355,1832.953267,2937.284047,1877.838227,2856.621684,NaN,...,NaN,NaN,1485.035260,2423.749044,1431.812097,2331.062515,NaN,NaN,1,1
14,15,NaN,NaN,1750.179260,2781.444355,1832.953267,2937.284047,1877.838227,2856.621684,NaN,...,NaN,NaN,1485.035260,2423.749044,1431.812097,2331.062515,NaN,NaN,1,1
15,16,NaN,NaN,1750.179260,2781.444355,1832.953267,2937.284047,1877.838227,2856.621684,NaN,...,NaN,NaN,1485.035260,2423.749044,1431.812097,2331.062515,NaN,NaN,1,1
16,17,1426.381654,2276.078247,1785.290707,2805.429255,NaN,NaN,1785.427309,2781.994323,NaN,...,1462.754979,2165.180356,1923.613651,2895.786804,1374.845383,2132.426309,NaN,NaN,1,1
17,18,1426.381654,2276.078247,1785.290707,2805.429255,NaN,NaN,1785.427309,2781.994323,NaN,...,1462.754979,2165.180356,1923.613651,2895.786804,1374.845383,2132.426309,NaN,NaN,1,1
18,19,1426.381654,2276.078247,1785.290707,2805.429255,NaN,NaN,1785.427309,2781.994323,NaN,...,1462.754979,2165.180356,1923.613651,2895.786804,1374.845383,2132.426309,NaN,NaN,1,1
19,20,1426.381654,2276.078247,1785.290707,2805.429255,NaN,NaN,1785.427309,2781.994323,NaN,...,1462.754979,2165.180356,1923.613651,2895.786804,1374.845383,2132.426309,NaN,NaN,1,1
20,21,1426.381654,2276.078247,1785.290707,2805.429255,NaN,NaN,1785.427309,2781.994323,NaN,...,1462.754979,2165.180356,1923.613651,2895.786804,1374.845383,2132.426309,NaN,NaN,1,1
21,22,1426.381654,2276.078247,1785.290707,2805.429255,NaN,NaN,1785.427309,2781.994323,NaN,...,1462.754979,2165.180356,1923.613651,2895.786804,1374.845383,2132.426309,NaN,NaN,1,1
22,23,1426.381654,2276.078247,1785.290707,2805.429255,NaN,NaN,1785.427309,2781.994323,NaN,...,1462.754979,2165.180356,1923.613651,2895.786804,1374.845383,2132.426309,NaN,NaN,1,1
23,24,1426.381654,2276.078247,1785.290707,2805.429255,NaN,NaN,1785.427309,2781.994323,NaN,...,1462.754979,2165.180356,1923.613651,2895.786804,1374.845383,2132.426309,NaN,NaN,1,1
24,25,NaN,NaN,2027.363305,3078.063989,NaN,NaN,NaN,NaN,NaN,...,1447.974744,2229.188904,1497.137717,2420.802064,1370.648414,2202.765777,NaN,NaN,1,1
25,26,NaN,NaN,2027.363305,3078.063989,NaN,NaN,NaN,NaN,NaN,...,1447.974744,2229.188904,1497.137717,2420.802064,1370.648414,2202.765777,NaN,NaN,1,1
26,27,NaN,NaN,2027.363305,3078.063989,NaN,NaN,NaN,NaN,NaN,...,1447.974744,2229.188904,1497.137717,2420.802064,1370.648414,2202.765777,NaN,NaN,1,1
27,28,NaN,NaN,2027.363305,3078.063989,NaN,NaN,NaN,NaN,NaN,...,1447.974744,2229.188904,1497.137717,2420.802064,1370.648414,2202.765777,NaN,NaN,1,1
28,29,NaN,NaN,2027.363305,3078.063989,NaN,NaN,NaN,NaN,NaN,...,1447.974744,2229.188904,1497.137717,2420.802064,1370.648414,2202.765777,NaN,NaN,1,1
29,30,NaN,NaN,2027.363305,3078.063989,NaN,NaN,NaN,NaN,NaN,...,1447.974744,2229.188904,1497.137717,2420.802064,1370.648414,2202.765777,NaN,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2166,337,1253.424204,2158.112215,1364.613794,2165.053441,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1478.623090,2490.535711,1426.000000,2199.000000,1657.059100,2741.887102,2,3
2167,338,1253.424204,2158.112215,1364.613794,2165.053441,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1478.623090,2490.535711,1426.000000,2199.000000,1657.059100,2741.887102,2,3
2168,339,1253.424204,2158.112215,1364.613794,2165.053441,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1478.623090,2490.535711,1426.000000,2199.000000,1657.059100,2741.887102,2,3
2169,340,1253.424204,2158.112215,1364.613794,2165.053441,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1478.623090,2490.535711,1426.000000,2199.000000,1657.059100,2741.887102,2,3
2170,341,1253.424204,2158.112215,1364.613794,2165.053441,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1478.623090,2490.535711,1426.000000,2199.000000,1657.059100,2741.887102,2,3
2171,342,1253.424204,2158.112215,1364.613794,2165.053441,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1478.623090,2490.535711,1426.000000,2199.000000,1657.059100,2741.887102,2,3
2172,343,1253.424204,2158.112215,1364.613794,2165.053441,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1478.623090,2490.535711,1426.000000,2199.000000,1657.059100,2741.887102,2,3
2173,344,1253.424204,2158.112215,1364.613794,2165.053441,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1478.623090,2490.535711,1426.000000,2199.000000,1657.059100,2741.887102,2,3
2174,345,1357.563090,2344.225563,1353.351065,2187.610695,NaN,NaN,1166.829765,1898.112241,1544.0,...,NaN,NaN,NaN,NaN,1451.000000,2364.250000,1657.163413,2780.606652,2,3
2175,346,1357.563090,2344.225563,1353.351065,2187.610695,NaN,NaN,1166.829765,1898.112241,1544.0,...,NaN,NaN,NaN,NaN,1451.000000,2364.250000,1657.163413,2780.606652,2,3
2176,347,1357.563090,2344.225563,1353.351065,2187.610695,NaN,NaN,1166.829765,1898.112241,1544.0,...,NaN,NaN,NaN,NaN,1451.000000,2364.250000,1657.163413,2780.606652,2,3
2177,348,1357.563090,2344.225563,1353.351065,2187.610695,NaN,NaN,1166.829765,1898.112241,1544.0,...,NaN,NaN,NaN,NaN,1451.000000,2364.250000,1657.163413,2780.606652,2,3
2178,349,1357.563090,2344.225563,1353.351065,2187.610695,NaN,NaN,1166.829765,1898.112241,1544.0,...,NaN,NaN,NaN,NaN,1451.000000,2364.250000,1657.163413,2780.606652,2,3
2179,350,1357.563090,2344.225563,1353.351065,2187.610695,NaN,NaN,1166.829765,1898.112241,1544.0,...,NaN,NaN,NaN,NaN,1451.000000,2364.250000,1657.163413,2780.606652,2,3
2180,351,1357.563090,2344.225563,1353.351065,2187.610695,NaN,NaN,1166.829765,1898.112241,1544.0,...,NaN,NaN,NaN,NaN,1451.000000,2364.250000,1657.163413,2780.606652,2,3
2181,352,1357.563090,2344.225563,1353.351065,2187.610695,NaN,NaN,1166.829765,1898.112241,1544.0,...,NaN,NaN,NaN,NaN,1451.000000,2364.250000,1657.163413,2780.606652,2,3
2182,353,1348.644106,2296.004655,1264.949773,2007.344785,NaN,NaN,1261.455919,1915.095838,NaN,...,1846.425113,2808.821987,1159.852482,1850.173560,1516.000000,2338.750000,NaN,NaN,2,3
2183,354,1348.644106,2296.004655,1264.949773,2007.344785,NaN,NaN,1261.455919,1915.095838,NaN,...,1846.425113,2808.821987,1159.852482,1850.173560,1516.000000,2338.750000,NaN,NaN,2,3
2184,355,1348.644106,2296.004655,1264.949773,2007.344785,NaN,NaN,1261.455919,1915.095838,NaN,...,1846.425113,2808.821987,1159.852482,1850.173560,1516.000000,2338.750000,NaN,NaN,2,3
2185,356,1348.644106,2296.004655,1264.949773,2007.344785,NaN,NaN,1261.455919,1915.095838,NaN,...,1846.425113,2808.821987,1159.852482,1850.173560,1516.000000,2338.750000,NaN,NaN,2,3
2186,357,1348.644106,2296.004655,1264.949773,2007.344785,NaN,NaN,1261.455919,1915.095838,NaN,...,1846.425113,2808.821987,1159.852482,1850.173560,1516.000000,2338.750000,NaN,NaN,2,3
2187,358,1348.644106,2296.004655,1264.949773,2007.344785,NaN,NaN,1261.455919,1915.095838,NaN,...,1846.425113,2808.821987,1159.852482,1850.173560,1516.000000,2338.750000,NaN,NaN,2,3
2188,359,1348.644106,2296.004655,1264.949773,2007.344785,NaN,NaN,1261.455919,1915.095838,NaN,...,1846.425113,2808.821987,1159.852482,1850.173560,1516.000000,2338.750000,NaN,NaN,2,3
2189,360,1348.644106,2296.004655,1264.949773,2007.344785,NaN,NaN,1261.455919,1915.095838,NaN,...,1846.425113,2808.821987,1159.852482,1850.173560,1516.000000,2338.750000,NaN,NaN,2,3
2190,361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1641.248043,2618.256431,2,3
2191,362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1641.248043,2618.256431,2,3
2192,363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1641.248043,2618.256431,2,3
2193,364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1641.248043,2618.256431,2,3
2194,365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1641.248043,2618.256431,2,3
2195,366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1641.248043,2618.256431,2,3

In [143]:
from functools import reduce
def return_index(x):
    yr=x[0]
    col=2*(yr-2000)-1
    sitee=x[1]
    cropp=x[4]
    doyy=x[2]
    idx=reduce(np.intersect1d,(np.where(meads_data['site'] == sitee)[0],np.where(meads_data['crop'] == cropp)[0],np.where(meads_data['doy'] == doyy)[0]))[0]
    return meads_data.loc[idx][col],meads_data.loc[idx][col+1]
lai[['b1','b2']]=lai.apply(return_index,axis=1).apply(pd.Series)
#lai[['b1','b2']]=lai['bands'].apply(pd.Series)
lai

,Year,Site,Sample (DOY),Green Leaf LAI,Crop,b1,b2
0,2001,1,149,0.0280863,1,721.502073,1463.212744
1,2001,1,164,0.369112,1,990.243115,2507.876996
2,2001,1,172,1.29104,1,NaN,NaN
3,2001,1,180,2.9447,1,NaN,NaN
4,2001,1,186,5.23946,1,285.863801,4311.224790
5,2001,1,193,6.03694,1,310.474266,4634.295054
6,2001,1,200,6.07868,1,310.474266,4634.295054
7,2001,1,220,5.6927,1,324.958178,4079.643464
8,2001,1,227,5.37085,1,334.768295,4014.405972
9,2001,2,149,0.0155399,1,807.490694,1865.711713
10,2001,2,164,0.31544,1,1106.291726,2523.197185
11,2001,2,172,1.02502,1,NaN,NaN
12,2001,2,180,2.6713,1,NaN,NaN
13,2001,2,190,5.27396,1,328.365442,4102.523168
14,2001,2,193,6.07975,1,280.556415,4680.243585
15,2001,2,201,6.07038,1,300.021814,4622.760434
16,2001,2,220,5.86785,1,401.410015,3741.708145
17,2001,2,232,5.64467,1,428.797292,3580.137546
18,2001,3,149,0.00829956,1,635.006567,1340.919473
19,2001,3,164,0.179909,1,1109.217152,2299.484493
20,2001,3,172,0.698763,1,NaN,NaN
21,2001,3,179,1.86674,1,NaN,NaN
22,2001,3,186,2.98488,1,404.896846,3588.148108
23,2001,3,192,3.88221,1,404.896846,3588.148108
24,2001,3,199,3.82949,1,352.373778,4084.859303
25,2001,3,219,3.51071,1,442.589917,3248.550986
26,2001,3,226,3.06002,1,436.966266,3107.141935
27,2002,1,149,0.0111055,1,1346.687643,2593.304336
28,2002,1,154,0.037466,1,1232.577589,2636.670033
29,2002,1,169,0.971284,1,750.802561,3195.633773
...,...,...,...,...,...,...,...
549,2016,2,149,0,2,1167.402383,2829.310070
550,2016,2,158,0.0571144,2,1356.289595,3073.278023
551,2016,2,165,0.174081,2,1491.678595,2871.543360
552,2016,2,172,0.345303,2,1211.296005,2970.225308
553,2016,2,179,0.838478,2,1006.485749,3266.250070
554,2016,2,187,1.11547,2,717.117164,3443.844201
555,2016,2,193,1.76878,2,509.458925,4011.670138
556,2016,2,200,2.92972,2,509.458925,4011.670138
557,2016,2,207,4.47334,2,302.160680,4546.352710
558,2016,2,214,4.66885,2,319.724514,4743.611816
559,2016,2,221,5.09577,2,286.944689,4698.521075
560,2016,2,228,4.77253,2,226.499637,4826.406403
561,2016,2,236,4.62399,2,261.356493,5053.207400
562,2016,2,256,3.73106,2,373.588671,4373.650465
563,2016,2,277,0.0876706,2,727.655332,2824.418421
564,2016,3,150,0,2,1437.592941,2612.231153
565,2016,3,158,0.0477973,2,1540.409519,2840.830393
566,2016,3,166,0.14652,2,1506.301185,2850.132111
567,2016,3,173,0.20489,2,1428.333570,2933.442355
568,2016,3,182,1.02088,2,1168.191375,3271.520080
569,2016,3,189,1.11185,2,773.464192,3501.649609
570,2016,3,195,2.04535,2,512.022970,4051.411760
571,2016,3,202,2.43293,2,256.241278,4809.001954
572,2016,3,209,3.25703,2,386.295159,4790.150162
573,2016,3,216,4.25422,2,386.295159,4790.150162
574,2016,3,223,4.60588,2,351.844181,5030.677485
575,2016,3,230,4.62898,2,180.798404,5142.417403
576,2016,3,250,4.08444,2,420.356377,4800.923409
577,2016,3,264,3.06765,2,408.366639,4059.237425
578,2016,3,279,0.0144714,2,754.882497,2954.012941

In [144]:
lai.to_pickle("LAI_test_data")

In [147]:
import pickle
pickle.load( open( "LAI_test_data", "rb" ) )

,Year,Site,Sample (DOY),Green Leaf LAI,Crop,b1,b2
0,2001,1,149,0.0280863,1,721.502073,1463.212744
1,2001,1,164,0.369112,1,990.243115,2507.876996
2,2001,1,172,1.29104,1,NaN,NaN
3,2001,1,180,2.9447,1,NaN,NaN
4,2001,1,186,5.23946,1,285.863801,4311.224790
5,2001,1,193,6.03694,1,310.474266,4634.295054
6,2001,1,200,6.07868,1,310.474266,4634.295054
7,2001,1,220,5.6927,1,324.958178,4079.643464
8,2001,1,227,5.37085,1,334.768295,4014.405972
9,2001,2,149,0.0155399,1,807.490694,1865.711713
10,2001,2,164,0.31544,1,1106.291726,2523.197185
11,2001,2,172,1.02502,1,NaN,NaN
12,2001,2,180,2.6713,1,NaN,NaN
13,2001,2,190,5.27396,1,328.365442,4102.523168
14,2001,2,193,6.07975,1,280.556415,4680.243585
15,2001,2,201,6.07038,1,300.021814,4622.760434
16,2001,2,220,5.86785,1,401.410015,3741.708145
17,2001,2,232,5.64467,1,428.797292,3580.137546
18,2001,3,149,0.00829956,1,635.006567,1340.919473
19,2001,3,164,0.179909,1,1109.217152,2299.484493
20,2001,3,172,0.698763,1,NaN,NaN
21,2001,3,179,1.86674,1,NaN,NaN
22,2001,3,186,2.98488,1,404.896846,3588.148108
23,2001,3,192,3.88221,1,404.896846,3588.148108
24,2001,3,199,3.82949,1,352.373778,4084.859303
25,2001,3,219,3.51071,1,442.589917,3248.550986
26,2001,3,226,3.06002,1,436.966266,3107.141935
27,2002,1,149,0.0111055,1,1346.687643,2593.304336
28,2002,1,154,0.037466,1,1232.577589,2636.670033
29,2002,1,169,0.971284,1,750.802561,3195.633773
...,...,...,...,...,...,...,...
549,2016,2,149,0,2,1167.402383,2829.310070
550,2016,2,158,0.0571144,2,1356.289595,3073.278023
551,2016,2,165,0.174081,2,1491.678595,2871.543360
552,2016,2,172,0.345303,2,1211.296005,2970.225308
553,2016,2,179,0.838478,2,1006.485749,3266.250070
554,2016,2,187,1.11547,2,717.117164,3443.844201
555,2016,2,193,1.76878,2,509.458925,4011.670138
556,2016,2,200,2.92972,2,509.458925,4011.670138
557,2016,2,207,4.47334,2,302.160680,4546.352710
558,2016,2,214,4.66885,2,319.724514,4743.611816
559,2016,2,221,5.09577,2,286.944689,4698.521075
560,2016,2,228,4.77253,2,226.499637,4826.406403
561,2016,2,236,4.62399,2,261.356493,5053.207400
562,2016,2,256,3.73106,2,373.588671,4373.650465
563,2016,2,277,0.0876706,2,727.655332,2824.418421
564,2016,3,150,0,2,1437.592941,2612.231153
565,2016,3,158,0.0477973,2,1540.409519,2840.830393
566,2016,3,166,0.14652,2,1506.301185,2850.132111
567,2016,3,173,0.20489,2,1428.333570,2933.442355
568,2016,3,182,1.02088,2,1168.191375,3271.520080
569,2016,3,189,1.11185,2,773.464192,3501.649609
570,2016,3,195,2.04535,2,512.022970,4051.411760
571,2016,3,202,2.43293,2,256.241278,4809.001954
572,2016,3,209,3.25703,2,386.295159,4790.150162
573,2016,3,216,4.25422,2,386.295159,4790.150162
574,2016,3,223,4.60588,2,351.844181,5030.677485
575,2016,3,230,4.62898,2,180.798404,5142.417403
576,2016,3,250,4.08444,2,420.356377,4800.923409
577,2016,3,264,3.06765,2,408.366639,4059.237425
578,2016,3,279,0.0144714,2,754.882497,2954.012941